resources:
  - name: twtest_repo
    type: GitRepo
    configuration:
      gitProvider: twgithub
      path: jfrogtw/jfrog-pipelines-gitstatus

pipelines:
  - name: twgit_status
    steps:
      - name: tw_execute_success_tests
        type: Bash
        configuration:
          inputResources:
            - name: twtest_repo

        execution:
          onStart:
            - update_commit_status twtest_repo --message "$pipeline_name" --context "$step_name"
            - echo "$is_success"
          onExecute:
            - echo "hello world"
          onFailure:
            - echo "$is_success"
          onComplete:
            - echo "$is_success"
            - update_commit_status twtest_repo --message "$pipeline_name" --context "$step_name"
      - name: tw_execute_failure_tests
        type: Bash
        configuration:
          inputResources:
            - name: twtest_repo
          inputSteps:
            - name: tw_execute_success_tests

        execution:
          onStart:
            - update_commit_status twtest_repo --message "$pipeline_name" --context "$step_name"
            - echo "$is_success"
          onExecute:
            - cd fail
          onFailure:
            - echo "$is_success"
          onComplete:
            - echo "$is_success"
            - update_commit_status twtest_repo --message "$pipeline_name" --context "$step_name"
