resources:
  - name: my_repo
    type: GitRepo
    configuration:
      gitProvider: twgithub
      path: jfrogtw/jfrog-pipelines-gitstatus

pipelines:
  - name: git_status_test
    steps:
      ##
      ## Step 1: Execute a simple, always successful test
      ##
      - name: success_test
        type: Bash
        configuration:
          inputResources:
            - name: my_repo
        execution:
          onStart:
            - update_commit_status my_repo --message "starting..." --context "$step_name"
          onExecute:
            - update_commit_status my_repo --message "running..." --context "$step_name"
            - echo "Hello World!"
          onFailure:
            - update_commit_status my_repo --message "Failed!" --context "$step_name"
          onSuccess:
            - update_commit_status my_repo --message "Succeeded :-)" --context "$step_name"
 
      ##
      ## Step 2: Execute a simple, always failing test
      ##
      - name: failure_test
        type: Bash
        configuration:
          inputResources:
            - name: my_repo
          inputSteps:
            - name: success_test
        execution:
          onStart:
            - update_commit_status my_repo --message "starting..." --context "$step_name"
          onExecute:
            - update_commit_status my_repo --message "running..." --context "$step_name"
            - cd fail               # No such directory -- guaranteed to fail
          onFailure:
            - update_commit_status my_repo --message "Failed!" --context "$step_name"
          onSuccess:
            - update_commit_status my_repo --message "Succeeded :-)" --context "$step_name"
